// Generated by https://quicktype.io

export interface PokeResponse {
    count:    number;
    next:     string;
    previous: string;
    results:  PokemonResult[];
}

export interface PokemonResult {
    name: string;
    url:  string;
}
